sudo: required
services:
  - docker
before_install:
  - docker build -f Dockerfile.dev -t hamzanaanani/docker-react .

scripts:
  - docker run -e CI=true hamzanaanani/docker-react npm run test

language: generic
