sudo: required
services:
  - docker
before_install:
  - docker build -f Dockerfile.dev -t hamzanaanani/docker-react .

scripts:
  - docker run -e CI=true hamzanaanani/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  region: "eu-west-3"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-3-907518596288"
  on:
    branch: master